cgbeacon2/server/blueprints/api_v1/views.py
# -*- coding: utf-8 -*-
import ast
import logging
import os

from cgbeacon2.__version__ import __version__
from cgbeacon2.constants import CHROMOSOMES, INVALID_TOKEN_AUTH
from cgbeacon2.models import Beacon
from cgbeacon2.utils.add import add_dataset as add_dataset_util
from cgbeacon2.utils.auth import authlevel, validate_token
from cgbeacon2.utils.parse import validate_add_params
from cgbeacon2.utils.update import update_event
from flask import (
    Blueprint,
    Response,
    current_app,
    flash,
    jsonify,
    render_template,
    request,
    send_from_directory,
)
from flask_executor import Executor
from flask_negotiate import consumes

from .controllers import (
    add_variants_task,
    create_allele_query,
    delete_variants_task,
    dispatch_query,
    stats,
    validate_add_data,
    validate_delete_data,
)

AUTHLEVEL = {"PUBLIC": "success", "REGISTERED": "warning", "CONTROLLED": "danger"}
EXISTS = {True: "success", False: "secondary"}

LOG = logging.getLogger(__name__)
api1_bp = Blueprint(
    "api_v1",
    __name__,
    template_folder="templates",
)


@api1_bp.route("/apiv1.0/img/<filename>")
def send_img(filename) -> Response:
    """Serve images to be displayed in web pages"""
    mimetype = "image/png"
    if filename.endswith(".svg"):
        mimetype = "image/svg+xml"
    return send_from_directory(
        os.path.join(current_app.root_path, "static"), filename, mimetype=mimetype
    )


@api1_bp.route("/", methods=["GET"])
@api1_bp.route("/apiv1.0/info", methods=["GET"])
@api1_bp.route("/apiv1.0/", methods=["GET"])
def info() -> Response:
    """Returns Beacon info data as a json object

    Example:
        curl -X GET 'http://localhost:5000/apiv1.0/'
        curl -X GET 'http://localhost:5000/apiv1.0/info'
        curl -X GET 'http://localhost:5000/'
    """
    beacon_config = current_app.config.get("BEACON_OBJ")
    beacon = Beacon(beacon_config, current_app.db)

    resp = jsonify(beacon.info())
    resp.status_code = 200
    return resp


@api1_bp.route("/", methods=["GET", "POST"])
@api1_bp.route("/apiv1.0/query_form", methods=["GET", "POST"])
def query_form() -> str:
    """The endpoint to a simple query form to interrogate this beacon
    Query is performed only on public access datasets contained in this beacon

    query_form page is accessible from a browser at this address:
    http://127.0.0.1:5000/apiv1.0/query_form
    """

    all_dsets = current_app.db["dataset"].find()
    all_dsets = [ds for ds in all_dsets]
    resp_obj = {}

    if request.method == "POST":
        # Create database query object
        customer_query, mongo_query, error = create_allele_query(request)

        if error:
            flash(error, "danger")

        else:  # query database
            # query database (it should return a datasetAlleleResponses object)
            response_type = customer_query.get("includeDatasetResponses", "NONE")
            query_datasets = customer_query.get("datasetIds", [])
            exists, ds_allele_responses = dispatch_query(mongo_query, response_type, query_datasets)
            resp_obj["exists"] = exists
            resp_obj["error"] = {"errorCode": 200}
            resp_obj["datasetAlleleResponses"] = ds_allele_responses

            flash(f"<small>Request received->{customer_query}</small>")

            if len(resp_obj.get("datasetAlleleResponses", [])) > 0:
                ds_responses = []
                # flash response from single datasets:
                for ds_resp in resp_obj["datasetAlleleResponses"]:
                    resp = f"""
                        <div class="row">
                            <div class="col-3">dataset: {ds_resp["datasetId"]}</div>
                            <div class="col-1"><span class="mr-1 badge badge-{AUTHLEVEL[ds_resp['info']['accessType']]}">{ds_resp['info']['accessType'].lower()}</span></div>
                            <div class="col-5">
                                <span class="badge badge-pill badge-light">sampleCount:{ds_resp["sampleCount"]}</span>
                                <span class="badge badge-pill badge-light">callCount:{ds_resp["callCount"]}</span>
                                <span class="badge badge-pill badge-light">variantCount:{ds_resp["variantCount"]}</span>
                            </div>
                            <div class="col-2">Allele exists: {ds_resp["exists"]}</div>
                        </div>
                        """
                    flash(resp, EXISTS[ds_resp["exists"]])

            elif resp_obj["exists"] is True:
                flash("Allele was found in this beacon", EXISTS[resp_obj["exists"]])
            else:
                flash("Allele could not be found", EXISTS[resp_obj["exists"]])

    return render_template(
        "queryform.html",
        chromosomes=CHROMOSOMES,
        dsets=all_dsets,
        software_version=__version__,
        stats=stats(),
        form=dict(request.form),
    )


@consumes("application/json")
@api1_bp.route("/apiv1.0/add_dataset", methods=["POST"])
def add_dataset() -> Response:
    """
    Endpoint used to create a new dataset in database.
    It is accepting json data from POST requests. If request params are OK returns 200 (success).
    If an error occurrs it returns error code plus error message.

    Example:
    ########### POST request ###########
    curl -X POST \
    -H 'Content-Type: application/json' \
    -H 'X-Auth-Token: DEMO' \
    -d '{"id": "test_public",
    "name": "Test public dataset", "description": "This is a test dataset",
    "build": "GRCh37", "authlevel": "public", "version": "v1.0",
    "url": "someurl.se", "update": "True"}' http://localhost:5000/apiv1.0/add_dataset
    """
    resp = None
    if validate_token(request, current_app.db) is False:
        resp = jsonify({"message": INVALID_TOKEN_AUTH["errorMessage"]})
        resp.status_code = INVALID_TOKEN_AUTH["errorCode"]
        return resp

    try:
        req_data = request.json
        dataset_obj = {
            "_id": req_data.get("id"),
            "name": req_data.get("name"),
            "description": req_data.get("description"),
            "assembly_id": req_data.get("build"),
            "authlevel": req_data.get("authlevel"),
            "version": str(req_data.get("version", "v1.0")),
            "external_url": req_data.get("url"),
        }

        inserted_id = add_dataset_util(
            database=current_app.db,
            dataset_dict=dataset_obj,
            update=ast.literal_eval(req_data.get("update", "False")),
        )
        if inserted_id:
            # register the event in the event collection
            update_event(current_app.db, req_data.get("id"), "dataset", True)

            resp = jsonify({"message": "Dataset collection was successfully updated"})
            resp.status_code = 200
        else:
            resp = jsonify({"message": "An error occurred while updating dataset collection"})
            resp.status_code = 422

    except Exception as ex:
        resp = jsonify({"message": str(ex)})
        resp.status_code = 422

    return resp


@consumes("application/json")
@api1_bp.route("/apiv1.0/add", methods=["POST"])
def add() -> Response:
    """
    Endpoint used to load variants into the database.
    It is accepting json data from POST requests. If request params are OK returns 200 (success).
    Then start a Thread that will save variants to database.

    Example:
    ########### POST request ###########
    curl -X POST \
    -H 'Content-Type: application/json' \
    -H 'X-Auth-Token: DEMO' \
    -d '{"dataset_id": "test_public",
    "vcf_path": "path/to/cgbeacon2/resources/demo/test_trio.vcf.gz",
    "samples" : ["ADM1059A1", "ADM1059A2"],
    "assemblyId": "GRCh37"}' http://localhost:5000/apiv1.0/add
    """
    resp = None
    # Check request auth token
    valid_token = validate_token(request, current_app.db)
    if valid_token is False:
        resp = jsonify({"message": INVALID_TOKEN_AUTH["errorMessage"]})
        resp.status_code = INVALID_TOKEN_AUTH["errorCode"]
        return resp

    # Check that request contains the required params
    validate_req = validate_add_params(request)
    if isinstance(validate_req, str):  # Validation failed
        resp = jsonify({"message": validate_req})
        resp.status_code = 422
        return resp

    # Check that request params are valid
    validate_req_data = validate_add_data(request)
    if isinstance(validate_req_data, str):  # Validation failed
        resp = jsonify({"message": validate_req_data})
        resp.status_code = 422
        return resp

    # Start loading variants thread
    executor = Executor()
    executor.init_app(current_app)
    executor.submit(add_variants_task, request)

    # Return success response
    resp = jsonify({"message": "Saving variants to Beacon"})
    resp.status_code = 202
    return resp


@consumes("application/json")
@api1_bp.route("/apiv1.0/delete", methods=["DELETE"])
def delete() -> Response:
    """
    Endpoint accepting json data from POST requests. If request params are OK returns 200 (success).
    Then start a Thread that will delete variants from database.
    ########### POST request ###########
    curl -X DELETE \
    -H 'Content-Type: application/json' \
    -H 'X-Auth-Token: DEMO' \
    -d '{"dataset_id": "test_public",
    "samples" : ["ADM1059A1", "ADM1059A2"]' http://localhost:5000/apiv1.0/delete
    """
    resp = None
    # Check request auth token
    valid_token = validate_token(request, current_app.db)
    if valid_token is False:
        resp = jsonify({"message": INVALID_TOKEN_AUTH["errorMessage"]})
        resp.status_code = INVALID_TOKEN_AUTH["errorCode"]
        return resp

    # Check that request params are valid
    validate_req_data = validate_delete_data(request)
    if isinstance(validate_req_data, str):  # Validation failed
        resp = jsonify({"message": validate_req_data})
        resp.status_code = 422
        return resp

cgbeacon2/server/blueprints/api_v1/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>cgbeacon2 landing page</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="shortcut icon" href="{{ url_for('api_v1.send_img', filename='clinGen.png') }}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="https://getbootstrap.com/docs/4.0/examples/sticky-footer/sticky-footer.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
  <link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
  <style>
  .alert {
    margin-bottom:0;
  }
  </style>
</head>

<header>
  <nav class="nav navbar-dark bg-dark justify-content-between">
    <a class="nav-item nav-link text-white" href="https://www.scilifelab.se/facilities/clinical-genomics-stockholm/" target="_blank" rel="noopener"><img class="mr-3" src="{{ url_for('api_v1.send_img', filename='logo.d59ae85.svg') }}" alt="Clinical Genomics logo" height="30">Clinical Genomics Beacon - SciLifeLab Stockholm</a>
    <a class="nav-item nav-link text-white d-flex align-items-center" href="https://github.com/Clinical-Genomics/cgbeacon2" target="_blank" rel="noopener"><em class="fab fa-github mr-3" style="font-size:30px;" align="middle"></em>Software v.{{software_version}}</a>
  </nav>
</header>
<body>
{% block body %}{% endblock %}
<br>
<div class="mb-3">
{% for category, message in get_flashed_messages(with_categories=True) %}
  <div class="alert alert-{{category}}">{{ message|safe }}</div>
{% endfor %}
</div>

<footer class="footer mt-3">
  <div class="row d-flex justify-content-around">
    <div>
      <a href="https://www.scilifelab.se" target="_blank" rel="noopener"><img src="{{url_for('api_v1.send_img', filename='scilifelab-logo.svg')}}" alt="SciLifeLab" height="50"></a>
    </div>
    <div>
      <a href="https://elixir-europe.org/" target="_blank" rel="noopener"><img src="{{url_for('api_v1.send_img', filename='elixir_logo.png')}}" alt="Elixir" height="50"></a>
    </div>
    <div>
      <a href="http://ki.se" target="_blank" rel="noopener"><img src="{{url_for('api_v1.send_img', filename='KI2.jpeg')}}" alt="Karolinska University Hospital" height="50"></a>
    </div>
    <div>
      <a href="https://www.ga4gh.org/" target="_blank" rel="noopener"><img src="{{url_for('api_v1.send_img', filename='ga4gh.png')}}" alt="Global Alliance for Genomics and Health" height="50"></a>
    </div>
    <div>
      <a href="https://beacon-network.org/#/" target="_blank" rel="noopener"><img src="{{url_for('api_v1.send_img', filename='beacon-network-logo-dark.svg')}}" alt="The Beacon Network" height="50"></a>
    </div>
  </div>
</footer>

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>
{% endblock %}

</body>

</html>

cgbeacon2/server/blueprints/api_v1/templates/queryform.html
{% extends "layout.html" %}
{% block body %}
  <div class="container-fluid">
    <nav aria-label="breadcrumb mt-3">
      <ol class="breadcrumb {% if stats.db_name and stats.n_datasets > 0 %} alert-success {% else %} alert-warning {% endif %}" ">
        <li class="breadcrumb-item"><i class="fas fa-database mr-1"></i>database:{{stats.db_name}}</li>
        <li class="breadcrumb-item"><i class="fas fa-archive mr-1"></i>n. datasets:<a href="#" data-toggle="modal" data-target="#dsDetails">{{stats.n_datasets}}</a></li>
        <li class="breadcrumb-item"><i class="fas fa-dna mr-1"></i>n. distinct variants:{{stats.variant_count}}</li>
      </ol>
    </nav>

    <!-- Modal window that shows available datasets info -->
    <div class="modal fade" id="dsDetails" tabindex="-1" role="dialog">
      <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
        {% if dsets %}
          <ul class="list-group list-group-flush">
          {% for dset in dsets %}
             <li class="list-group-item">
               <div class="row">
                 <div class="col-8">
                   <b>{{dset.name}} ({{dset._id}})</b>
                   {% if dset.authlevel == "controlled" %}
                    <span class="badge badge-danger">controlled</span>
                   {% elif dset.authlevel == "registered" %}
                    <span class="badge badge-warning">registered</span>
                   {% else %}
                    <span class="badge badge-success">public</span>
                   {% endif %}
                   <span class="badge badge-primary">{{dset.assembly_id}}</span>
                   <span class="badge badge-secondary">{{dset.version}}</span>
                   <br>
                   <span class="badge badge-pill badge-light">variant count:{{dset.variant_count or 0}}</span>
                   <span class="badge badge-pill badge-light">allele count:{{dset.allele_count or 0}}</span>
                 </div>
                 <div class="col-4">
                   <small>Created:{% if dset.created %} {{dset.created.strftime('%Y-%m-%d')}} {% else %} n.a. {% endif %} / Last modified:{% if dset.updated %} {{dset.updated.strftime('%Y-%m-%d')}} {% else %} n.a. {% endif %}</small>
                </div>
              </div>
              <div class="row">
                <div class="col-12">{{dset.description}}</div>
              </div>
             </li>
          {% endfor %}
          </ul>
        {% else %}
          No datasets available for this beacon
        {% endif %}
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div> <!-- end of modal content -->
      </div> <!-- end of modal dialog -->
    </div>
    <!-- End of datasets info modal -->

    <div class="mt-3">
      <form action="{{url_for('api_v1.query_form')}}" method="post">
        <div class="row">
          <div class="col-md-12">
            <p class="text-right d-flex align-items-center"><h4 style="color: #ef7c00;">Variant search</h4></p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-2">
            <label for="assemblyId">Genome build<span style="color: #ef7c00;" data-toggle="tooltip" data-placement="top" title="required field">*</span></label>
            <select class="form-control" name="assemblyId" required>
              <option>GRCh37</option>
              <option {% if form.assemblyId == "GRCh38" %} selected="selected" {% endif %}>GRCh38</option>
            </select>
          </div>
          <div class="col-md-2">
            <label for="referenceName">Chromosome<span style="color: #ef7c00;" data-toggle="tooltip" data-placement="top" title="required field">*</span></label>
            <select class="form-control" name="referenceName" required>
              {% for chrom in chromosomes %}
                <option {% if chrom == form.referenceName %} selected="selected" {% endif %} >{{chrom}}</option>
              {% endfor %}
            </select>
          </div>
          <div class="col-md-2">
            <label for="start">Start position<span style="color: #ef7c00;" data-toggle="tooltip" data-placement="top" title="0-based coordinate">**</span></label>
            <input type="number" class="form-control" id="start" name="start" value={{form.start}}>
          </div>
          <div class="col-md-2">
            <label for="end">End position<span style="color: #ef7c00;" data-toggle="tooltip" data-placement="top" title="0-based coordinate">**</span></label>
            <input type="number" class="form-control" id="end" name="end" value={{form.end}}>
          </div>

          <div class="col-md-4">
            <label for="datasetIds">Dataset</label>
                <select multiple class="selectpicker" name="datasetIds">
                  <option value="" disabled selected>Select datasets</option>
                  {%for dset in dsets %}
                    <option value="{{dset['_id']}}">{{ dset['_id'] }}</option>
                  {%endfor %}
                </select>
          </div>
        </div> <!--end of first row-->
        <div class="row mt-3">
          <div class="form-check col-md-2">
            <input type="checkbox" id="type" {% if form == {} or form.variantType == "" %} checked {%endif%} data-toggle="toggle" data-on="Single nucleotides" data-off="Structural variants" data-onstyle="primary" data-offstyle="success">
          </div>

          <div class="col-md-2">
            <label for="referenceBases">Reference bases<span style="color: #ef7c00;" data-toggle="tooltip" data-placement="top" title="required field">*</span></label>
            <input type="text" class="form-control" id="referenceBases" name="referenceBases" placeholder="ex: T" value="{{form.referenceBases}}" required>
          </div>

          <div id="snvsDiv" class="col-md-2" {% if form != {} and form.variantType != "" %} style="display:none;" {%endif%}>
            <label for="alternateBases">Alternate bases</label>
            <input type="text" class="form-control" id="alternateBases" name="alternateBases" placeholder="ex: C" value="{{form.alternateBases}}">
          </div>

          <div id="svsDiv" class="col-md-2" {% if form == {} or form.variantType == "" %} style="display:none" {%endif%}>
            <label for="variantType">Variant type</label>
            <select class="form-control" name="variantType">
              {% for sv in ["", "INS", "DEL", "DUP", "INV", "BND"] %}
                <option>{{sv}}</option>
              {% endfor %}
            </select>
          </div>

          <div class="form-check col-md-4 offset-2">
            <!-- DatasetAlleleResponse=NONE-->
            <input class="form-check-input" type="radio" name="includeDatasetResponses" id="includeDatasetResponses" value="NONE" {% if 'includeDatasetResponses' not in form or form.includeDatasetResponses == "NONE"%} checked {% endif %}>
            <label class="form-check-label" for="includeDatasetResponses">
              Check if allele is present in any dataset
            </label><br>
            <!-- DatasetAlleleResponse=ALL-->
            <input class="form-check-input" type="radio" name="includeDatasetResponses" id="includeDatasetResponses" value="ALL" {% if form.includeDatasetResponses == "ALL"%} checked {% endif %}>
            <label class="form-check-label" for="includeDatasetResponses">
              Return dataset-level info (all datasets)
            </label><br>
            <!-- DatasetAlleleResponse=HIT-->
            <input class="form-check-input" type="radio" name="includeDatasetResponses" id="includeDatasetResponses" value="HIT" {% if form.includeDatasetResponses == "HIT"%} checked {% endif %}>
            <label class="form-check-label" for="includeDatasetResponses">
              Return dataset-level info (all datasets with hits)
            </label><br>
            <!-- DatasetAlleleResponse=MISS-->
            <input class="form-check-input" type="radio" name="includeDatasetResponses" id="includeDatasetResponses" value="MISS" {% if form.includeDatasetResponses == "MISS"%} checked {% endif %}>
            <label class="form-check-label" for="includeDatasetResponses">
              Return dataset-level info (all datasets with NO hits)
            </label>
          </div>
        </div>
        <!--Range coordinates-->
        <div class="row mt-3" id="rangeCoords">
          <div class="form-check col-md-2">
            <input type="checkbox" id="range" data-toggle="toggle" data-on="Exact positions" data-off="Range query"
              data-onstyle="dark" data-offstyle="secondary" {% if form == {} or form.startMin == "" %} checked {%endif%}>
          </div>
          <div id="rangeDiv" class="row" {% if form == {} or form.startMin == "" %} style="display:none" {%endif%}>
            <div class="col-sm-3">
              <label for="startMin">Min start<span style="color: #ef7c00;" data-toggle="tooltip" data-placement="top" title="0-based coordinate">**</span></label>
              <input type="number" class="form-control" id="startMin" name="startMin" value={{form.startMin}}>
            </div>
            <div class="col-sm-3">
              <label for="startMax">Max start<span style="color: #ef7c00;" data-toggle="tooltip" data-placement="top" title="0-based coordinate">**</span></label>
              <input type="number" class="form-control" id="startMax" name="startMax" value={{form.startMax}}>
            </div>
            <div class="col-sm-3">
              <label for="endMin">Min end<span style="color: #ef7c00;" data-toggle="tooltip" data-placement="top" title="0-based coordinate">**</span></label>
              <input type="number" class="form-control" id="endMin" name="endMin" value={{form.endMin}}>
            </div>
            <div class="col-sm-3">
              <label for="endMax">Max end<span style="color: #ef7c00;" data-toggle="tooltip" data-placement="top" title="0-based coordinate">**</span></label>
              <input type="number" class="form-control" id="endMax" name="endMax" value={{form.endMax}}>
            </div>
          </div>
        </div>
         <br>
        <div class="row">
          <div class="col-md-5"></div>
            <div class="col-md-3">
              <button type="submit" name="query" value="submit" class="btn btn-warning">Search SciLifeLab Beacon</button>
            </div>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

{% block scripts %}
  {{ super() }}
  <script>
  $('select[multiple]').selectpicker({
        width: '100%'
  });

  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })

  $(function() {
    $('#type').change(function() {
      if($(this).prop("checked")){
        $('#snvsDiv').show();
        $("#alternateBases").prop('required',true);
        $('#svsDiv').hide();
        $.each($(".variantType option:selected"), function () {
          $(this).prop('selected', false); // <-- HERE
        });
      }
      else{
        $('#svsDiv').show();
        $('#snvsDiv').hide();
        $("#alternateBases").prop('required',false);
        $('#alternateBases').val("");
      }
    });

    $('#range').change(function() {
      if($(this).prop("checked")){
        $('#rangeDiv').hide();
        $('#start').prop('disabled',false);
        $('#end').prop('disabled',false);
        $('#startMin').val("");
        $('#startMax').val("");
        $('#endMin').val("");
        $('#endMax').val("");
      }
      else{
        $('#rangeDiv').show();
        $('#start').prop('disabled',true);
        $('#start').val("");
        $('#end').prop('disabled',true);
        $('#end').val("");
      }
    })
  });
  </script>

{% endblock%}